In [1]:
import pandas as pd
from pathlib import Path

# base_dir = Path(__file__).resolve().parents[1]
# raw_dir = base_dir / "data" / "raw"
# raw_dir.mkdir(parents=True, exist_ok=True)

NameError: name '__file__' is not defined

In [4]:
laps_df = pd.read_csv("../data/raw/2025_monaco_race.csv")
laps_df.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:36.090000,VER,1,0 days 00:01:27.020000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:38.394000,...,True,Red Bull Racing,0 days 00:56:08.809000,2025-05-25 13:03:09.195,12,4.0,False,NaN,False,False
1,0 days 00:59:22.408000,VER,1,0 days 00:01:46.318000,2.0,1.0,NaN,NaN,0 days 00:00:34.949000,0 days 00:00:45.145000,...,True,Red Bull Racing,0 days 00:57:36.090000,2025-05-25 13:04:36.476,16,4.0,False,NaN,False,False
2,0 days 01:01:11.223000,VER,1,0 days 00:01:48.815000,3.0,1.0,NaN,NaN,0 days 00:00:32.110000,0 days 00:00:47.430000,...,True,Red Bull Racing,0 days 00:59:22.408000,2025-05-25 13:06:22.794,6,4.0,False,NaN,False,False
3,0 days 01:02:51.513000,VER,1,0 days 00:01:40.290000,4.0,1.0,NaN,NaN,0 days 00:00:31.006000,0 days 00:00:47.889000,...,True,Red Bull Racing,0 days 01:01:11.223000,2025-05-25 13:08:11.609,671,4.0,False,NaN,False,False
4,0 days 01:04:12.313000,VER,1,0 days 00:01:20.800000,5.0,1.0,NaN,NaN,0 days 00:00:21.744000,0 days 00:00:37.485000,...,True,Red Bull Racing,0 days 01:02:51.513000,2025-05-25 13:09:51.899,1,4.0,False,NaN,False,True

# Standardize Colums

In [6]:
# Driver → driver
# LapNumber → lap
# Stint → stint
# Compound → compound
# LapTime → lap_time
# Position → position
laps_df = laps_df.rename(columns={"Driver":"driver","DriverNumber":"driver_number", "LapNumber":"lap", "Stint":"stint", "Compound":"compound", "LapTime":"lap_time", "Position":"position"})

laps_df.head()

,Time,driver,driver_number,lap_time,lap,stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:36.090000,VER,1,0 days 00:01:27.020000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:38.394000,...,True,Red Bull Racing,0 days 00:56:08.809000,2025-05-25 13:03:09.195,12,4.0,False,NaN,False,False
1,0 days 00:59:22.408000,VER,1,0 days 00:01:46.318000,2.0,1.0,NaN,NaN,0 days 00:00:34.949000,0 days 00:00:45.145000,...,True,Red Bull Racing,0 days 00:57:36.090000,2025-05-25 13:04:36.476,16,4.0,False,NaN,False,False
2,0 days 01:01:11.223000,VER,1,0 days 00:01:48.815000,3.0,1.0,NaN,NaN,0 days 00:00:32.110000,0 days 00:00:47.430000,...,True,Red Bull Racing,0 days 00:59:22.408000,2025-05-25 13:06:22.794,6,4.0,False,NaN,False,False
3,0 days 01:02:51.513000,VER,1,0 days 00:01:40.290000,4.0,1.0,NaN,NaN,0 days 00:00:31.006000,0 days 00:00:47.889000,...,True,Red Bull Racing,0 days 01:01:11.223000,2025-05-25 13:08:11.609,671,4.0,False,NaN,False,False
4,0 days 01:04:12.313000,VER,1,0 days 00:01:20.800000,5.0,1.0,NaN,NaN,0 days 00:00:21.744000,0 days 00:00:37.485000,...,True,Red Bull Racing,0 days 01:02:51.513000,2025-05-25 13:09:51.899,1,4.0,False,NaN,False,True

# Detect pit stops

In [10]:
sorted_laps = laps_df.sort_values(by=['driver', 'lap'])
sorted_laps.head()

# for each driver compare stints

,Time,driver,driver_number,lap_time,lap,stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,position,Deleted,DeletedReason,FastF1Generated,IsAccurate
428,0 days 00:57:40.549000,ALB,23,0 days 00:01:31.479000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:40.146000,...,False,Williams,0 days 00:56:08.809000,2025-05-25 13:03:09.195,12,10.0,False,NaN,False,False
429,0 days 00:59:32.701000,ALB,23,0 days 00:01:52.152000,2.0,1.0,NaN,NaN,0 days 00:00:38.401000,0 days 00:00:47.108000,...,False,Williams,0 days 00:57:40.549000,2025-05-25 13:04:40.935,16,10.0,False,NaN,False,False
430,0 days 01:01:21.047000,ALB,23,0 days 00:01:48.346000,3.0,1.0,NaN,NaN,0 days 00:00:30.845000,0 days 00:00:48.338000,...,False,Williams,0 days 00:59:32.701000,2025-05-25 13:06:33.087,6,10.0,False,NaN,False,False
431,0 days 01:02:57.053000,ALB,23,0 days 00:01:36.006000,4.0,1.0,NaN,NaN,0 days 00:00:29.942000,0 days 00:00:44.769000,...,False,Williams,0 days 01:01:21.047000,2025-05-25 13:08:21.433,671,10.0,False,NaN,False,False
432,0 days 01:04:17.518000,ALB,23,0 days 00:01:20.465000,5.0,1.0,NaN,NaN,0 days 00:00:21.014000,0 days 00:00:38.074000,...,False,Williams,0 days 01:02:57.053000,2025-05-25 13:09:57.439,1,10.0,False,NaN,False,True